#!/bin/sh

# Copyright 2019 Carlos Machado.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

usage() {
    cat <<-EOF
This script combines Cloudflare's cfssl CLI tool with kubectl to:
1. Generate a certificate signed by a Certificate Authority (CA);
2. Store the resulting certificate as a kubernetes TLS secret.

Usage: $0 [-c CACERT] [-f] [-h] [-i CONFIG] [-k CAKEY] [-n NAMESPACE] [-o PREFIX] [-p PROFILE] [-r CSR] [-s SECRET]

Options:
    -c  Path to the CA certificate file (default is 'int-ca.pem').
    -f  Force the creation of the kubernetes secret (default is 'no').
        If this option is present and the secret already exists, it will be deleted first.
    -h  Prints this message and exits.
    -i  Path to the cfssl configuration file (default is 'ca-config.json').
    -k  Path to the CA private key file (default is 'int-ca.key').
    -n  Kubernetes namespace where the resulting secret will be stored (default is 'default').
    -o  Name prefix for the resulting certificate files (default is 'cert').
        By default, it generates 3 files named: cert.pem, cert-key.pem and cert.csr
    -p  Profile to use to issue the certificate (default is 'server').
        The supported profiles are specified in the cfssl configuration file.
    -r  Path to the Certificate Signing Request (CSR) file (default is 'server-csr.json').
    -s  Kubernetes secret name (default is 'server-tls').
EOF
}

ca_cert='int-ca.key'
ca_key='int-ca.pem'
config_file='ca-config.json'
csr_file='server-csr.json'
output_file='cert'
profile='server'
k8s_secret='server-tls'
k8s_namespace='default'
force='no'

while getopts 'c:fhi:k:n:o:p:r:s:' options; do
    case "${options}" in
        c)
            ca_cert="${OPTARG}"
            ;;
        f)
            force='yes'
            ;;
        h)
            usage
            exit 0
            ;;
        i)
            config_file="${OPTARG}"
            ;;
        k)
            ca_key="${OPTARG}"
            ;;
        n)
            k8s_namespace="${OPTARG}"
            ;;
        o)
            output_file="${OPTARG}"
            ;;
        p)
            profile="${OPTARG}"
            ;;
        r)
            csr_file="${OPTARG}"
            ;;
        s)
            k8s_secret="${OPTARG}"
            ;;
        :)
            echo "[ERROR] -${OPTARG} requires an argument." 1>&2
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

echo "[INFO] $0 command-line arguments:"
echo "ca_cert       = ${ca_cert}"
echo "ca_key        = ${ca_key}"
echo "config_file   = ${config_file}"
echo "csr_file      = ${csr_file}"
echo "force         = ${force}"
echo "k8s_namespace = ${k8s_namespace}"
echo "k8s_secret    = ${k8s_secret}"
echo "output_file   = ${output_file}"
echo "profile       = ${profile}"

# generate certificate
cfssl gencert -ca "${ca_cert}" -ca-key "${ca_key}" -config "${config_file}" -profile "${profile}" "${csr_file}" | cfssljson -bare "${output_file}"

if [ "${force}" = 'yes' ]; then
    kubectl -n ${k8s_namespace} delete secret ${k8s_secret} > /dev/null 2>&1 || true
fi
kubectl -n ${k8s_namespace} create secret tls ${k8s_secret} --cert="${output_file}.pem" --key="${output_file}-key.pem"
